// @flow
export const MODULE_NAME = 'mailTemplatesService';

// Categories

export const READ_MAIL_TPL_CATEGORIES_ACTION = 'READ_MAIL_TPL_CATEGORIES_ACTION';
export const READ_MAIL_TPL_CATEGORIES_SUCCEED_ACTION = 'READ_MAIL_TPL_CATEGORIES_SUCCEED_ACTION';
export const READ_MAIL_TPL_CATEGORIES_FAILED_ACTION = 'READ_MAIL_TPL_CATEGORIES_FAILED_ACTION';

export const DEL_MAIL_TPL_CATEGORIES_ACTION = 'DEL_MAIL_TPL_CATEGORIES_ACTION';
export const DEL_MAIL_TPL_CATEGORIES_SUCCEED_ACTION = 'DEL_MAIL_TPL_CATEGORIES_SUCCEED_ACTION';
export const DEL_MAIL_TPL_CATEGORIES_FAILED_ACTION = 'DEL_MAIL_TPL_CATEGORIES_FAILED_ACTION';

export const CREATE_MAIL_TPL_CATEGORY_ACTION = 'CREATE_MAIL_TPL_CATEGORY_ACTION';
export const CREATE_MAIL_TPL_CATEGORY_SUCCEED_ACTION = 'CREATE_MAIL_TPL_CATEGORY_SUCCEED_ACTION';
export const CREATE_MAIL_TPL_CATEGORY_FAILED_ACTION = 'CREATE_MAIL_TPL_CATEGORY_FAILED_ACTION';

export const UPDATE_MAIL_TPL_CATEGORY_ACTION = 'UPDATE_MAIL_TPL_CATEGORY_ACTION';
export const UPDATE_MAIL_TPL_CATEGORY_SUCCEED_ACTION = 'UPDATE_MAIL_TPL_CATEGORY_SUCCEED_ACTION';
export const UPDATE_MAIL_TPL_CATEGORY_FAILED_ACTION = 'UPDATE_MAIL_TPL_CATEGORY_FAILED_ACTION';

// Messages

export const READ_MAIL_TPL_MESSAGES_ACTION = 'READ_MAIL_TPL_MESSAGES_ACTION';
export const READ_MAIL_TPL_MESSAGES_SUCCEED_ACTION = 'READ_MAIL_TPL_MESSAGES_SUCCEED_ACTION';
export const READ_MAIL_TPL_MESSAGES_FAILED_ACTION = 'READ_MAIL_TPL_MESSAGES_FAILED_ACTION';

export const DEL_MAIL_TPL_MESSAGES_ACTION = 'DEL_MAIL_TPL_MESSAGES_ACTION';
export const DEL_MAIL_TPL_MESSAGES_SUCCEED_ACTION = 'DEL_MAIL_TPL_MESSAGES_SUCCEED_ACTION';
export const DEL_MAIL_TPL_MESSAGES_FAILED_ACTION = 'DEL_MAIL_TPL_MESSAGES_FAILED_ACTION';

export const CREATE_MAIL_TPL_MESSAGE_ACTION = 'CREATE_MAIL_TPL_MESSAGE_ACTION';
export const CREATE_MAIL_TPL_MESSAGE_SUCCEED_ACTION = 'CREATE_MAIL_TPL_MESSAGE_SUCCEED_ACTION';
export const CREATE_MAIL_TPL_MESSAGE_FAILED_ACTION = 'CREATE_MAIL_TPL_MESSAGE_FAILED_ACTION';

export const UPDATE_MAIL_TPL_MESSAGE_ACTION = 'UPDATE_MAIL_TPL_MESSAGE_ACTION';
export const UPDATE_MAIL_TPL_MESSAGE_SUCCEED_ACTION = 'UPDATE_MAIL_TPL_MESSAGE_SUCCEED_ACTION';
export const UPDATE_MAIL_TPL_MESSAGE_FAILED_ACTION = 'UPDATE_MAIL_TPL_MESSAGE_FAILED_ACTION';
